export enum Traco {
  Agil = 'Ágil',
  Acuidade = 'Acuidade',
  VersatilCt = 'Versatil Ct',
  VersatilPf = 'Versatil Pf',
  VersatilCn = 'Versatil Cn',
  Arremesso = "Arremesso",
  Arremesso3m = 'Arremesso 3m',
  Arremesso6m = 'Arremesso 6m',
  DuasMaosD8 = 'Duas Mãos d8',
  DuasMaosD12 = 'Duas Mãos d12',
  Derrubar = 'Derrubar',
  MortalD6 = 'Mortal d6',
  MortalD10 = 'Mortal d10',
  Alcance = 'Alcance',
  NaoLetal = 'Não-Letal',
  Desarmar = 'Desarmar',
  Amplitude = 'Amplitude',
  Anao = 'Anão',
  Gnomo = 'Gnomo',
  Gemea = 'Gêmea',
  Divino = 'Divino',
  FatalD10 = 'Fatal d10',
  Monge = "Monge",
  Empurrar = "Empurrar",
  MaoLivre = "Mão Livre"
}

export enum TracoDescricao {
  Agil = 'A penalidade por ataques múltiplos que você sofre com esta arma é de –4 (em vez de –5) em seu segundo ataque no turno e de –8 (em vez de –10) em seu terceiro ataque (e ataques subsequentes) no turno',
  Acuidade = 'Você pode utilizar seu modificador de Destreza em vez de seu modificador de Força em rolagens de ataque usando esta arma corpo a corpo. Você ainda utiliza seu modificador de Força para calcular o dano',
  VersatilCt = 'Uma arma versátil pode ser usada para causar um tipo diferente de dano do listado na seção de Dano. Este traço indica o tipo de dano alternativo. Por exemplo: uma arma perfurante que é versátil Ct pode ser usada para causar dano perfurante ou cortante. Você escolhe o tipo de dano a cada ataque que fizer.',
  VersatilPf = 'Uma arma versátil pode ser usada para causar um tipo diferente de dano do listado na seção de Dano. Este traço indica o tipo de dano alternativo. Por exemplo: uma arma perfurante que é versátil Ct pode ser usada para causar dano perfurante ou cortante. Você escolhe o tipo de dano a cada ataque que fizer.',
  Arremesso3m = 'Você pode arremessar esta arma como um ataque à distância; quando arremessada, ela é considerada uma arma à distância. Uma arma de arremesso adiciona seu modificador de Força ao dano da mesma forma que uma arma corpo a corpo. Quando este traço aparecer em uma arma corpo a corpo, ele também incluirá o incremento',
  Arremesso6m = 'Você pode arremessar esta arma como um ataque à distância; quando arremessada, ela é considerada uma arma à distância. Uma arma de arremesso adiciona seu modificador de Força ao dano da mesma forma que uma arma corpo a corpo. Quando este traço aparecer em uma arma corpo a corpo, ele também incluirá o incremento',
  DuasMaosD8 = 'Esta arma pode ser empunhada com duas mãos. Fazer isso altera o dado de dano da arma para o valor indicado. Esta mudança se aplica a todos os dados de dano da arma, assim como os dados de runas impactantes',
  DuasMaosD12 = 'Esta arma pode ser empunhada com duas mãos. Fazer isso altera o dado de dano da arma para o valor indicado. Esta mudança se aplica a todos os dados de dano da arma, assim como os dados de runas impactantes',
  Derrubar = 'Você pode usar esta arma para Derrubar com a perícia Atletismo mesmo se não tiver uma mão livre. Para isso, você utiliza o alcance da arma (se for diferente do seu) e aplica o bônus de item da arma em rolagens de ataque (se houver) como um bônus de item no teste de Atletismo. Se obtiver uma falha crítica no teste para Derrubar enquanto usar essa arma, você pode escolher soltá-la para sofrer os efeitos de uma falha em vez dos efeitos de uma falha crítica',
  MortalD10 = 'Em um acerto crítico, a arma adiciona um dado de dano de arma do tamanho listado. Role este dado depois de dobrar o dano da arma. Este dado extra aumenta para dois dados se a arma possuir uma runa impactante maior e para três dados se a arma possuir uma runa impactante superior. Por exemplo: uma rapieira com uma runa impactante maior causa 2d8 extras de dano perfurante em um acerto crítico. Uma habilidade que alterar o tamanho do dado de dano normal da arma não altera o tamanho do dado mortal dela',
  Alcance = 'Esta arma é longa e pode ser usada para atacar criaturas a até 3 metros em vez de apenas criaturas adjacentes. Criaturas que já possuam alcance com o membro (ou membros) que empunha a arma, aumentam seu alcance com a arma em 1,5 metros',
  NaoLetal = 'Ataques com esta arma são não-letais e são usados para deixar criaturas inconscientes em vez de matá-las. Você pode usar uma arma não-letal para fazer ataques letais com –2 de penalidade de circunstância',
  Desarmar = 'Você pode usar esta arma para Desarmar com a perícia Atletismo mesmo se não tiver uma mão livre. Para isso, você utiliza o alcance da arma (se for diferente do seu) e aplica o bônus de item da arma em rolagens de ataque (se houver) como um bônus de item no teste de Atletismo. Se obtiver uma falha crítica no teste para Desarmar enquanto usar essa arma, você pode escolher soltá-la para sofrer os efeitos de uma falha em vez dos efeitos de uma falha crítica. Em um sucesso crítico, você ainda precisa de uma mão livre se quiser pegar o item.',
  Amplitude = 'Esta arma faz ataques amplos ou giratórios, tornando mais fácil atacar vários inimigos. Quando atacar com ela, você recebe +1 de bônus de circunstância em sua rolagem de ataque se já tiver tentado atacar um alvo diferente neste turno usando esta arma',
  Anao = 'Anões manufaturam e usam estas armas.',
  Gnomo = 'Gnomos manufaturam e usam estas armas',
  Gemea = 'Estas armas são usadas em pares, complementando uma à outra. Quando atacar com uma arma gêmea, você adiciona um bônus de circunstância à rolagem de dano igual à quantidade de dados de dano da arma se já tiver atacado com uma arma diferente desse mesmo tipo neste turno. As armas devem ser do mesmo tipo para se beneficiarem deste traço, mas não precisam possuir as mesmas runas',
  Divino = 'Divino',
  FatalD10 = 'O traço fatal inclui um tamanho de dado. Em um acerto crítico, o dado de dano da arma aumenta para esse tamanho listado (fazendo-o usar esse tamanho de dado em vez do tamanho de dano normal da arma para calcular o dano desse acerto crítico) e você adiciona um dado de dano extra do tamanho listado a esse dano.'
}
