export enum Traco {
  Agil = '<a href="https://2e.aonprd.com/Traits.aspx?ID=170" class="link-light">Ágil</a>',
  Acuidade = '<a href="https://2e.aonprd.com/Traits.aspx?ID=179" class="link-light">Acuidade</a>',
  Agarrar = '<a href="https://2e.aonprd.com/Traits.aspx?ID=184" class="link-light">Agarrar</a>',
  Alcance = '<a href="https://2e.aonprd.com/Traits.aspx?ID=192" class="link-light">Alcance</a>',
  Amplitude = '<a href="https://2e.aonprd.com/Traits.aspx?ID=194" class="link-light">Amplitude</a>',
  Anao = '<a href="https://2e.aonprd.com/Traits.aspx?ID=54" class="link-light">Anão</a>',
  Anexada = '<a href="https://2e.aonprd.com/Traits.aspx?ID=171" class="link-light">Anexada</a>',
  Aparar = '<a href="https://2e.aonprd.com/Traits.aspx?ID=190" class="link-light">Aparar</a>',
  Apunhaladora = '<a href="https://2e.aonprd.com/Traits.aspx?ID=172" class="link-light">Apunhaladora</a>',
  Arremesso = '<a href="https://2e.aonprd.com/Traits.aspx?ID=195" class="link-light">Arremesso</a>',
  Arremesso3m = '<a href="https://2e.aonprd.com/Traits.aspx?ID=195" class="link-light">Arremesso 3m</a>',
  Arremesso6m = '<a href="https://2e.aonprd.com/Traits.aspx?ID=195" class="link-light">Arremesso 6m</a>',
  Arremesso9m = '<a href="https://2e.aonprd.com/Traits.aspx?ID=195" class="link-light">Arremesso 9m</a>',
  Arremesso12m = '<a href="https://2e.aonprd.com/Traits.aspx?ID=195" class="link-light">Arremesso 12m</a>',
  Derrubar = '<a href="https://2e.aonprd.com/Traits.aspx?ID=196" class="link-light">Derrubar</a>',
  DerrubarADistancia = '<a href="https://2e.aonprd.com/Traits.aspx?ID=251" class="link-light">Derrubar à Distância</a>',
  Desarmado = '<a href="https://2e.aonprd.com/Traits.aspx?ID=199" class="link-light">Desarmado</a>',
  Desarmar = '<a href="https://2e.aonprd.com/Traits.aspx?ID=175" class="link-light">Desarmar</a>',
  DuasMaosD6 = '<a href="https://2e.aonprd.com/Traits.aspx?ID=198" class="link-light">Duas Mãos d6</a>',
  DuasMaosD8 = '<a href="https://2e.aonprd.com/Traits.aspx?ID=198" class="link-light">Duas Mãos d8</a>',
  DuasMaosD10 = '<a href="https://2e.aonprd.com/Traits.aspx?ID=198" class="link-light">Duas Mãos d10</a>',
  DuasMaosD12 = '<a href="https://2e.aonprd.com/Traits.aspx?ID=198" class="link-light">Duas Mãos d12</a>',
  Elfo = '<a href="https://2e.aonprd.com/Traits.aspx?ID=58" class="link-light">Elfo</a>',
  Empurrar = '<a href="https://2e.aonprd.com/Traits.aspx?ID=193" class="link-light">Empurrar</a>',
  Energica = '<a href="https://2e.aonprd.com/Traits.aspx?ID=180" class="link-light">Enérgica</a>',
  FatalD6 = '<a href="https://2e.aonprd.com/Traits.aspx?ID=178" class="link-light">Fatal d6</a>',
  FatalD8 = '<a href="https://2e.aonprd.com/Traits.aspx?ID=178" class="link-light">Fatal d8</a>',
  FatalD10 = '<a href="https://2e.aonprd.com/Traits.aspx?ID=178" class="link-light">Fatal d10</a>',
  FatalD12 = '<a href="https://2e.aonprd.com/Traits.aspx?ID=178" class="link-light">Fatal d12</a>',
  Gemea = '<a href="https://2e.aonprd.com/Traits.aspx?ID=197" class="link-light">Gêmea</a>',
  Gnomo = '<a href="https://2e.aonprd.com/Traits.aspx?ID=80" class="link-light">Gnomo</a>',
  Goblin = '<a href="https://2e.aonprd.com/Traits.aspx?ID=81" class="link-light">Goblin</a>',
  Halfling = '<a href="https://2e.aonprd.com/Traits.aspx?ID=87" class="link-light">Halfling</a>',
  Hobgoblin = '<a href="https://2e.aonprd.com/Traits.aspx?ID=268" class="link-light">Hobgoblin</a>',
  Incomum = '<a href="https://2e.aonprd.com/Traits.aspx?ID=159" class="link-light">Incomum</a>',
  JustaD6 = '<a href="https://2e.aonprd.com/Traits.aspx?ID=186" class="link-light">Justa d6</a>',
  MaoLivre = '<a href="https://2e.aonprd.com/Traits.aspx?ID=181" class="link-light">Mão Livre</a>',
  MiraFatald10 = '<a href="https://2e.aonprd.com/Traits.aspx?ID=404" class="link-light">Mira Fatal d10</a>',
  MiraFatald12 = '<a href="https://2e.aonprd.com/Traits.aspx?ID=404" class="link-light">Mira Fatal d12</a>',
  Monge = '<a href="https://2e.aonprd.com/Traits.aspx?ID=112" class="link-light">Monge</a>',
  MortalD6 = '<a href="https://2e.aonprd.com/Traits.aspx?ID=174" class="link-light">Mortal d6</a>',
  MortalD8 = '<a href="https://2e.aonprd.com/Traits.aspx?ID=174" class="link-light">Mortal d8</a>',
  MortalD10 = '<a href="https://2e.aonprd.com/Traits.aspx?ID=174" class="link-light">Mortal d10</a>',
  MortalD12 = '<a href="https://2e.aonprd.com/Traits.aspx?ID=174" class="link-light">Mortal d12</a>',
  NaoLetal = '<a href="https://2e.aonprd.com/Traits.aspx?ID=188" class="link-light">Não-Letal</a>',
  Orc = '<a href="https://2e.aonprd.com/Traits.aspx?ID=124" class="link-light">Orc</a>',
  Oscilante = '<a href="https://2e.aonprd.com/Traits.aspx?ID=173" class="link-light">Oscilante</a>',
  VersatilCn = '<a href="https://2e.aonprd.com/Traits.aspx?ID=200" class="link-light">Versatil Cn</a>',
  VersatilCt = '<a href="https://2e.aonprd.com/Traits.aspx?ID=200" class="link-light">Versatil Ct</a>',
  VersatilPf = '<a href="https://2e.aonprd.com/Traits.aspx?ID=200" class="link-light">Versatil Pf</a>',
  Voleio6m = '<a href="https://2e.aonprd.com/Traits.aspx?ID=201" class="link-light">Voleio 6m</a>',
  Voleio9m = '<a href="https://2e.aonprd.com/Traits.aspx?ID=201" class="link-light">Voleio 9m</a>',
  Voleio15m = '<a href="https://2e.aonprd.com/Traits.aspx?ID=201" class="link-light">Voleio 15m</a>',
  Null = 'Null',
  Kobold = '<a href="https://2e.aonprd.com/Traits.aspx?ID=224" class="link-light">Kobold</a>',
  Azarketi = '<a href="https://2e.aonprd.com/Traits.aspx?ID=336" class="link-light">Azarketi</a>',
  Grippli = '<a href="https://2e.aonprd.com/Ancestries.aspx?ID=46" class="link-light">Grippli</a>',
  Conrasu = '<a href="https://2e.aonprd.com/Traits.aspx?ID=343" class="link-light">Conrasu</a>',
  PovoGato = '<a href="https://2e.aonprd.com/Traits.aspx?ID=211" class="link-light">Povo-Gato</a>',
  PovoRato = '<a href="https://2e.aonprd.com/Traits.aspx?ID=234" class="link-light">Povo-Rato</a>',
  Tengu = '<a href="https://2e.aonprd.com/Traits.aspx?ID=240" class="link-light">Tengu</a>',
  Raro = '<a href="https://2e.aonprd.com/Traits.aspx?ID=137" class="link-light">Raro</a>',
  Propulsiva = '<a href="https://2e.aonprd.com/Traits.aspx?ID=191" class="link-light">Propulsiva</a>',
  ModularPBS = '<a href="https://2e.aonprd.com/Traits.aspx?ID=271" class="link-light">Modular (Cn, Pf, Ct)</a>',
  ModularPAgarrarSAmplitude = '<a href="https://2e.aonprd.com/Traits.aspx?ID=271" class="link-light">Modular (Pf e Agarrar ou Ct e Amplitude)</a>',
  UniaoCritica = '<a href="https://2e.aonprd.com/Traits.aspx?ID=402" class="link-light">União Crítica*</a>',
  Juncao = '<a href="https://2e.aonprd.com/Traits.aspx?ID=417" class="link-light">Junção*</a>',
  Veicular = '<a href="https://2e.aonprd.com/Traits.aspx?ID=493" class="link-light">Veicular*</a>',
  AnexadaBestaArmaFogo = '<a href="https://2e.aonprd.com/Traits.aspx?ID=171" class="link-light">Anexada à Besta ou Arma de Fogo</a>',
  Demolidora = '<a href="https://2e.aonprd.com/Traits.aspx?ID=488" class="link-light">Demolidora*</a>',
  Escalar = '<a href="https://2e.aonprd.com/Traits.aspx?ID=347" class="link-light">Escalar</a>',
  Preso = '<a href="https://2e.aonprd.com/Traits.aspx?ID=252" class="link-light">Preso*</a>',
  Treinamento = '<a href="https://2e.aonprd.com/Traits.aspx?ID=492" class="link-light">Treinamento*</a>',
  GemeaEspada = '<a href="https://2e.aonprd.com/Traits.aspx?ID=197" class="link-light">Gemea (Espada)</a>',
  GemeaBainha = '<a href="https://2e.aonprd.com/Traits.aspx?ID=197" class="link-light">Gemea (Bainha)</a>',
  Injecao = '<a href="https://2e.aonprd.com/Traits.aspx?ID=407" class="link-light">Injeção*</a>',
  Falange = '<a href="https://2e.aonprd.com/Traits.aspx?ID=471" class="link-light">Falange*</a>',
  AnexadaEscudo = '<a href="https://2e.aonprd.com/Traits.aspx?ID=171" class="link-light">Anexada ao Escudo</a>',
  Ghoran = '<a href="https://2e.aonprd.com/Traits.aspx?ID=352" class="link-light">Ghoran</a>',
  Geniano = '<a href="https://2e.aonprd.com/Traits.aspx?ID=340" class="link-light">Geniano</a>',
  Ressonante = '<a href="https://2e.aonprd.com/Traits.aspx?ID=345" class="link-light">Ressonante</a>',
  Clockwork = '<a href="https://2e.aonprd.com/Traits.aspx?ID=331" class="link-light">Clockwork</a>',
  Dificultadora = '<a href="https://2e.aonprd.com/Traits.aspx?ID=344" class="link-light">Dificultadora</a>',
  Recarga1 = '<a href="https://2e.aonprd.com/Traits.aspx?ID=254" class="link-light">Recarga*</a>',
  Vanara = '<a href="https://2e.aonprd.com/Traits.aspx?ID=368" class="link-light">Vanara</a>',
  Vishkanya = '<a href="https://2e.aonprd.com/Traits.aspx?ID=369" class="link-light">Vishkanya</a>',
  Alquimico = '<a href="https://2e.aonprd.com/Traits.aspx?ID=6" class="link-light">Alquimico</a>',
  Concussivo = '<a href="https://2e.aonprd.com/Traits.aspx?ID=401" class="link-light">Concussivo*</a>',
  Repeticao = '<a href="https://2e.aonprd.com/Traits.aspx?ID=374" class="link-light">Repetição*</a>',
  Recuo = '<a href="https://2e.aonprd.com/Traits.aspx?ID=409" class="link-light">Recuo*</a>',
  Remendado = '<a href="https://2e.aonprd.com/Traits.aspx?ID=400" class="link-light">Remendado*</a>',
  Disperso3m = '<a href="https://2e.aonprd.com/Traits.aspx?ID=413" class="link-light">Disperso 3m*</a>',
  Disperso1MetroMeio = '<a href="https://2e.aonprd.com/Traits.aspx?ID=413" class="link-light">Disperso 1.5m*</a>',
  Retornante = '<a href="https://2e.aonprd.com/Traits.aspx?ID=489" class="link-light">Retornante*</a>',
  Capacidade2 = '<a href="https://2e.aonprd.com/Traits.aspx?ID=399" class="link-light">Capacidade 2*</a>',
  Capacidade3 = '<a href="https://2e.aonprd.com/Traits.aspx?ID=399" class="link-light">Capacidade 3*</a>',
  Capacidade4 = '<a href="https://2e.aonprd.com/Traits.aspx?ID=399" class="link-light">Capacidade 4*</a>',
  Capacidade5 = '<a href="https://2e.aonprd.com/Traits.aspx?ID=399" class="link-light">Capacidade 5*</a>',
  CanoDuplo = '<a href="https://2e.aonprd.com/Traits.aspx?ID=403" class="link-light">Cano Duplo*</a>',
  Ocultavel = `<a href="https://2e.aonprd.com/Traits.aspx?ID=327" class="link-light">Ocultável`,
}

export const getDescricaoTraco = (traco: Traco): string => {
  switch(traco){
    case Traco.Acuidade: return `Você pode utilizar seu modificador de Destreza em vez de seu modificador de Força em rolagens de ataque usando esta arma corpo a corpo. Você ainda utiliza seu modificador de Força para calcular o dano`
    case Traco.Agarrar: return 'Você pode usar esta arma para Agarrar com a perícia Atletismo mesmo se não tiver uma mão livre. Para isso, você utiliza o alcance da arma (se for diferente do seu) e aplica o bônus de item da arma em rolagens de ataque (se houver) como um bônus de item no teste de Atletismo. Se obtiver uma falha crítica no teste para Agarrar enquanto usar essa arma, você pode escolher soltá-la para sofrer os efeitos de uma falha em vez dos efeitos de uma falha crítica.'
    case Traco.Agil: return `A penalidade por ataques múltiplos que você sofre com esta arma é de –4 (em vez de –5) em seu segundo ataque no turno e de –8 (em vez de –10) em seu terceiro ataque (e ataques subsequentes) no turno`
    case Traco.Alcance: return 'Esta arma é longa e pode ser usada para atacar criaturas a até 3 metros em vez de apenas criaturas adjacentes. Criaturas que já possuam alcance com o membro (ou membros) que empunha a arma, aumentam seu alcance com a arma em 1,5 metros'
    case Traco.Amplitude: return 'Esta arma faz ataques amplos ou giratórios, tornando mais fácil atacar vários inimigos. Quando atacar com ela, você recebe +1 de bônus de circunstância em sua rolagem de ataque se já tiver tentado atacar um alvo diferente neste turno usando esta arma'
    case Traco.Anao: return 'Anões manufaturam e usam estas armas'
    case Traco.Anexada: return 'Uma arma anexada deve ser combinada com outro equipamento para ser usada. Este traço lista a qual tipo de item a arma deve ser anexada. Você deve estar empunhando ou usando o item ao qual a arma está anexada para poder atacar com ela. Por exemplo, espinhos de escudo são anexados a um escudo, permitindo que você ataque com os espinhos em vez de com uma pancada com escudo, mas apenas se estiver empunhando o escudo. Uma arma anexada normalmente é aparafusada ou construída junto do item ao qual é anexada — e normalmente um item pode ter apenas uma arma anexada a ele. Uma arma anexada pode ser afixada em um item com 10 minutos de trabalho e um teste bem-sucedido de Manufatura CD 10; isto inclui o tempo necessário para remover a arma do item anterior, se necessário. Se um item for destruído, sua arma anexada normalmente pode ser recuperada.'
    case Traco.Aparar: return 'Esta arma pode ser usada defensivamente para bloquear ataques. Enquanto empunhar esta arma e possuir proficiência treinado ou melhor com ela, você pode gastar uma ação de Interagir para posicionar sua arma defensivamente, recebendo +1 de bônus de circunstância na CA até o começo do seu próximo turno'
    case Traco.Apunhaladora: return 'Quando você atinge uma criatura desprevenida, esta arma causa 1 ponto de dano de precisão em adição ao seu dano normal. O dano de precisão aumenta para 2 pontos se ela for uma arma +3.'
    case Traco.Arremesso: return 'Você pode arremessar esta arma como um ataque à distância; quando arremessada, ela é considerada uma arma à distância. Uma arma de arremesso adiciona seu modificador de Força ao dano da mesma forma que uma arma corpo a corpo. Quando este traço aparecer em uma arma corpo a corpo, ele também incluirá o incremento'
    case Traco.Arremesso3m: return 'Você pode arremessar esta arma como um ataque à distância; quando arremessada, ela é considerada uma arma à distância. Uma arma de arremesso adiciona seu modificador de Força ao dano da mesma forma que uma arma corpo a corpo. Quando este traço aparecer em uma arma corpo a corpo, ele também incluirá o incremento'
    case Traco.Arremesso6m: return 'Você pode arremessar esta arma como um ataque à distância; quando arremessada, ela é considerada uma arma à distância. Uma arma de arremesso adiciona seu modificador de Força ao dano da mesma forma que uma arma corpo a corpo. Quando este traço aparecer em uma arma corpo a corpo, ele também incluirá o incremento'
    case Traco.Arremesso9m: return 'Você pode arremessar esta arma como um ataque à distância; quando arremessada, ela é considerada uma arma à distância. Uma arma de arremesso adiciona seu modificador de Força ao dano da mesma forma que uma arma corpo a corpo. Quando este traço aparecer em uma arma corpo a corpo, ele também incluirá o incremento'
    case Traco.Arremesso12m: return 'Você pode arremessar esta arma como um ataque à distância; quando arremessada, ela é considerada uma arma à distância. Uma arma de arremesso adiciona seu modificador de Força ao dano da mesma forma que uma arma corpo a corpo. Quando este traço aparecer em uma arma corpo a corpo, ele também incluirá o incremento'
    case Traco.Derrubar: return 'Você pode usar esta arma para Derrubar com a perícia Atletismo mesmo se não tiver uma mão livre. Para isso, você utiliza o alcance da arma (se for diferente do seu) e aplica o bônus de item da arma em rolagens de ataque (se houver) como um bônus de item no teste de Atletismo. Se obtiver uma falha crítica no teste para Derrubar enquanto usar essa arma, você pode escolher soltá-la para sofrer os efeitos de uma falha em vez dos efeitos de uma falha crítica';
    case Traco.DerrubarADistancia: return 'A arma pode ser usada para Derrubar com a perícia Atletismo a uma distância de até o primeiro incremento de distância da arma. O teste de perícia sofre –2 de penalidade de circunstância. Você pode adicionar o bônus de item da arma em rolagens de ataque como um bônus no teste. Como ao usar uma arma para Derrubar, uma derrubada a distância não causa qualquer dano. Este traço normalmente só aparece em armas de arremesso'
    case Traco.Desarmado: return 'Um ataque desarmado utiliza seu corpo em vez de uma arma manufaturada. Um ataque desarmado não é uma arma — embora seja categorizado com armas em grupos de armas e possa ter traços de armas. Como é parte de seu corpo, um ataque desarmado não pode sofrer Desarmar. Ele também não ocupa uma mão, embora um punho ou outro apêndice similar siga as mesmas regras que uma arma de mão livre.'
    case Traco.Desarmar: return 'Você pode usar esta arma para Desarmar com a perícia Atletismo mesmo se não tiver uma mão livre. Para isso, você utiliza o alcance da arma (se for diferente do seu) e aplica o bônus de item da arma em rolagens de ataque (se houver) como um bônus de item no teste de Atletismo. Se obtiver uma falha crítica no teste para Desarmar enquanto usar essa arma, você pode escolher soltá-la para sofrer os efeitos de uma falha em vez dos efeitos de uma falha crítica. Em um sucesso crítico, você ainda precisa de uma mão livre se quiser pegar o item.';
    case Traco.DuasMaosD6: return 'Esta arma pode ser empunhada com duas mãos. Fazer isso altera o dado de dano da arma para o valor indicado. Esta mudança se aplica a todos os dados de dano da arma, assim como os dados de runas impactantes'
    case Traco.DuasMaosD8: return 'Esta arma pode ser empunhada com duas mãos. Fazer isso altera o dado de dano da arma para o valor indicado. Esta mudança se aplica a todos os dados de dano da arma, assim como os dados de runas impactantes'
    case Traco.DuasMaosD10: return 'Esta arma pode ser empunhada com duas mãos. Fazer isso altera o dado de dano da arma para o valor indicado. Esta mudança se aplica a todos os dados de dano da arma, assim como os dados de runas impactantes'
    case Traco.DuasMaosD12: return 'Esta arma pode ser empunhada com duas mãos. Fazer isso altera o dado de dano da arma para o valor indicado. Esta mudança se aplica a todos os dados de dano da arma, assim como os dados de runas impactantes'
    case Traco.Elfo: return 'Elfos manufaturam e usam estas armas'
    case Traco.Empurrar: return 'Você pode usar esta arma para Empurrar com a perícia Atletismo mesmo se não tiver uma mão livre. Para isso, você utiliza o alcance da arma (se for diferente do seu) e aplica o bônus de item da arma em rolagens de ataque (se houver) como um bônus de item no teste de Atletismo. Se obtiver uma falha crítica no teste para Empurrar enquanto usar essa arma, você pode escolher soltá-la para sofrer os efeitos de uma falha em vez dos efeitos de uma falha crítica'
    case Traco.Energica: return 'Esta arma se torna mais perigosa conforme acumula impulso. Quando atacar com ela mais de uma vez em seu turno, o segundo ataque recebe um bônus de circunstância de dano igual à quantidade de dados de dano da arma, e cada ataque subsequente recebe um bônus de circunstância igual ao dobro da quantidade de dados de dano da arma.'
    case Traco.FatalD6: return 'O traço fatal inclui um tamanho de dado. Em um acerto crítico, o dado de dano da arma aumenta para esse tamanho listado (fazendo-o usar esse tamanho de dado em vez do tamanho de dano normal da arma para calcular o dano desse acerto crítico) e você adiciona um dado de dano extra do tamanho listado a esse dano.'
    case Traco.FatalD8: return 'O traço fatal inclui um tamanho de dado. Em um acerto crítico, o dado de dano da arma aumenta para esse tamanho listado (fazendo-o usar esse tamanho de dado em vez do tamanho de dano normal da arma para calcular o dano desse acerto crítico) e você adiciona um dado de dano extra do tamanho listado a esse dano.'
    case Traco.FatalD10: return 'O traço fatal inclui um tamanho de dado. Em um acerto crítico, o dado de dano da arma aumenta para esse tamanho listado (fazendo-o usar esse tamanho de dado em vez do tamanho de dano normal da arma para calcular o dano desse acerto crítico) e você adiciona um dado de dano extra do tamanho listado a esse dano.'
    case Traco.FatalD12: return 'O traço fatal inclui um tamanho de dado. Em um acerto crítico, o dado de dano da arma aumenta para esse tamanho listado (fazendo-o usar esse tamanho de dado em vez do tamanho de dano normal da arma para calcular o dano desse acerto crítico) e você adiciona um dado de dano extra do tamanho listado a esse dano.'
    case Traco.Gemea: return 'Estas armas são usadas em pares, complementando uma à outra. Quando atacar com uma arma gêmea, você adiciona um bônus de circunstância à rolagem de dano igual à quantidade de dados de dano da arma se já tiver atacado com uma arma diferente desse mesmo tipo neste turno. As armas devem ser do mesmo tipo para se beneficiarem deste traço, mas não precisam possuir as mesmas runas'
    case Traco.Gnomo: return 'Gnomos manufaturam e usam estas armas'
    case Traco.Goblin: return 'Goblins manufaturam e usam estas armas'
    case Traco.Halfling: return 'Halflings manufaturam e usam estas armas'
    case Traco.Hobgoblin: return 'Hobgoblins manufaturam e usam estas armas'
    case Traco.Incomum: return 'Um elemento de regra de raridade incomum requer treinamento especial ou pertence a uma cultura ou parte do mundo em particular. Algumas escolhas de personagem dão acesso a opções incomuns e o MJ pode escolher conceder acesso para qualquer um.'
    case Traco.JustaD6: return 'A arma é apropriada para combates montados sendo apoiada por suportes na armadura ou meios similares. Quando estiver montado, se tiver se movido pelo menos 3 metros na ação anterior ao seu ataque, adicione um bônus de circunstância ao dano desse ataque igual à quantidade de dados de dano dessa arma. Além disso, enquanto estiver montado, você pode empunhar a arma em uma mão, mudando o dado de dano para o valor listado'
    case Traco.MaoLivre: return 'Esta arma não ocupa sua mão, normalmente por ser embutida em sua armadura. Uma arma de mão livre não pode ser alvo de Desarmar. Você pode usar a mão coberta por sua arma de mão livre para empunhar outros itens, executar ações de manipular e assim por diante. Você não pode atacar com uma arma de mão livre se estiver empunhando qualquer coisa nessa mão ou se de alguma forma estiver usando essa mão. Quando não estiver empunhando nada nem usando essa mão de outra forma, você pode usar tanto habilidades que requeiram uma mão livre quanto habilidades que requeiram que você esteja empunhando uma arma nessa mão. Você só pode ter uma arma de mão livre em cada uma de suas mãos'
    case Traco.MiraFatald10: return 'É possível segurar o cabo desta arma sob um braço para dispará-la com uma única mão, contanto que a outra mão não esteja segurando outra arma, escudo ou qualquer outra coisa que seria necessária para movimentar e posicionar a arma, garantindo que ela não escorregue sob o braço. No entanto, se você usar ambas as mãos, a arma pode realizar ataques fatais. Ao empunhar a arma com as duas mãos, ela ganha a característica fatal com o dado de dano indicado. Segurar a arma sob o braço de maneira estável o suficiente para dispará-la é significativamente mais complicado do que simplesmente soltar uma mão da arma, então, para alternar entre os dois modos de empunhadura, você deve fazê-lo com uma ação de Interação, em vez de Soltar ou como parte do recarregamento.'
    case Traco.MiraFatald12: return 'É possível segurar o cabo desta arma sob um braço para dispará-la com uma única mão, contanto que a outra mão não esteja segurando outra arma, escudo ou qualquer outra coisa que seria necessária para movimentar e posicionar a arma, garantindo que ela não escorregue sob o braço. No entanto, se você usar ambas as mãos, a arma pode realizar ataques fatais. Ao empunhar a arma com as duas mãos, ela ganha a característica fatal com o dado de dano indicado. Segurar a arma sob o braço de maneira estável o suficiente para dispará-la é significativamente mais complicado do que simplesmente soltar uma mão da arma, então, para alternar entre os dois modos de empunhadura, você deve fazê-lo com uma ação de Interação, em vez de Soltar ou como parte do recarregamento.'
    case Traco.Monge: return 'Muitos monges aprendem a usar estas armas'
    case Traco.MortalD6: return 'Em um acerto crítico, a arma adiciona um dado de dano de arma do tamanho listado. Role este dado depois de dobrar o dano da arma. Este dado extra aumenta para dois dados se a arma possuir uma runa impactante maior e para três dados se a arma possuir uma runa impactante superior. Por exemplo: uma rapieira com uma runa impactante maior causa 2d8 extras de dano perfurante em um acerto crítico. Uma habilidade que alterar o tamanho do dado de dano normal da arma não altera o tamanho do dado mortal dela'
    case Traco.MortalD8: return 'Em um acerto crítico, a arma adiciona um dado de dano de arma do tamanho listado. Role este dado depois de dobrar o dano da arma. Este dado extra aumenta para dois dados se a arma possuir uma runa impactante maior e para três dados se a arma possuir uma runa impactante superior. Por exemplo: uma rapieira com uma runa impactante maior causa 2d8 extras de dano perfurante em um acerto crítico. Uma habilidade que alterar o tamanho do dado de dano normal da arma não altera o tamanho do dado mortal dela'
    case Traco.MortalD10: return 'Em um acerto crítico, a arma adiciona um dado de dano de arma do tamanho listado. Role este dado depois de dobrar o dano da arma. Este dado extra aumenta para dois dados se a arma possuir uma runa impactante maior e para três dados se a arma possuir uma runa impactante superior. Por exemplo: uma rapieira com uma runa impactante maior causa 2d8 extras de dano perfurante em um acerto crítico. Uma habilidade que alterar o tamanho do dado de dano normal da arma não altera o tamanho do dado mortal dela'
    case Traco.MortalD12: return 'Em um acerto crítico, a arma adiciona um dado de dano de arma do tamanho listado. Role este dado depois de dobrar o dano da arma. Este dado extra aumenta para dois dados se a arma possuir uma runa impactante maior e para três dados se a arma possuir uma runa impactante superior. Por exemplo: uma rapieira com uma runa impactante maior causa 2d8 extras de dano perfurante em um acerto crítico. Uma habilidade que alterar o tamanho do dado de dano normal da arma não altera o tamanho do dado mortal dela'
    case Traco.NaoLetal: return 'Ataques com esta arma são não-letais e são usados para deixar criaturas inconscientes em vez de matá-las. Você pode usar uma arma não-letal para fazer ataques letais com –2 de penalidade de circunstância'
    case Traco.Ocultavel: return 'Esta arma é designada para ser imperceptível ou facilmente ocultada. Você recebe +2 de bônus de circunstância em testes e CDs de Furtividade para esconder ou ocultar uma arma com este traço.'
    case Traco.Orc: return 'Orcs manufaturam e usam estas armas'
    case Traco.Oscilante: return 'Você pode aproveitar o impulso de um ataque errado com esta arma para seu próximo ataque. Depois de errar com esta arma no seu turno, você recebe +1 de bônus de circunstância em seu próximo ataque realizado com esta arma antes do final de seu turno.'
    case Traco.VersatilCn: return 'Uma arma versátil pode ser usada para causar um tipo diferente de dano do listado na seção de Dano. Este traço indica o tipo de dano alternativo. Por exemplo: uma arma perfurante que é versátil Ct pode ser usada para causar dano perfurante ou cortante. Você escolhe o tipo de dano a cada ataque que fizer.'
    case Traco.VersatilCt: return 'Uma arma versátil pode ser usada para causar um tipo diferente de dano do listado na seção de Dano. Este traço indica o tipo de dano alternativo. Por exemplo: uma arma perfurante que é versátil Ct pode ser usada para causar dano perfurante ou cortante. Você escolhe o tipo de dano a cada ataque que fizer.'
    case Traco.VersatilPf: return 'Uma arma versátil pode ser usada para causar um tipo diferente de dano do listado na seção de Dano. Este traço indica o tipo de dano alternativo. Por exemplo: uma arma perfurante que é versátil Ct pode ser usada para causar dano perfurante ou cortante. Você escolhe o tipo de dano a cada ataque que fizer.'
    case Traco.Voleio6m: return 'Esta arma à distância é menos efetiva a curta distância. Seus ataques contra alvos dentro da distância listada sofrem –2 de penalidade'
    case Traco.Voleio9m: return 'Esta arma à distância é menos efetiva a curta distância. Seus ataques contra alvos dentro da distância listada sofrem –2 de penalidade'
    case Traco.Voleio15m: return 'Esta arma à distância é menos efetiva a curta distância. Seus ataques contra alvos dentro da distância listada sofrem –2 de penalidade'
    case Traco.Null: return "Null"
    case Traco.Kobold: return 'Kobolds manufaturam e usam estas armas'
    case Traco.Azarketi: return 'Azarketis manufaturam e usam estas armas'
    case Traco.Grippli: return 'Gripplis manufaturam e usam estas armas'
    case Traco.Conrasu: return 'Conrasus manufaturam e usam estas armas'
    case Traco.PovoGato: return 'Povo-Felinos manufaturam e usam estas armas'
    case Traco.PovoRato: return 'Povo-Ratos manufaturam e usam estas armas'
    case Traco.Tengu: return 'Tengus manufaturam e usam estas armas'
    case Traco.Raro: return 'Esta raridade indica que um elemento de regra é muito difícil de encontrar no mundo de jogo. Uma habilidade, item ou magia rara é disponível para jogadores somente se o MJ decidir inclui-lo no jogo, normalmente através de descoberta durante o jogo.'
    case Traco.Propulsiva: return 'Você adiciona metade de seu modificador de Força (se positivo) às rolagens de dano com uma arma à distância propulsiva. Se tiver um modificador de Força negativo, você adiciona seu modificador de Força inteiro'
    case Traco.ModularPBS: return 'A arma possui várias configurações para as quais você pode trocar usando uma ação de Interagir. Normalmente, trocar entre as configurações de uma arma modular permite que ela cause diferentes tipos de dano (listados no traço, como “modular Cn, Ct ou Pf”), embora seja possível que a descrição de uma arma modular liste configurações mais complicadas'
    case Traco.ModularPAgarrarSAmplitude: return 'A arma possui várias configurações para as quais você pode trocar usando uma ação de Interagir. Normalmente, trocar entre as configurações de uma arma modular permite que ela cause diferentes tipos de dano (listados no traço, como “modular Cn, Ct ou Pf”), embora seja possível que a descrição de uma arma modular liste configurações mais complicadas'
    case Traco.UniaoCritica: return 'A fusão crítica é uma característica para armas de Junção que concede duas opções adicionais para o efeito de especialização crítica ao usar a versão de combate corpo a corpo da arma combinada para realizar um ataque corpo a corpo enquanto a arma de longo alcance está carregada. Se você optar por usar uma delas, ela substituirá o efeito normal de especialização crítica do uso corpo a corpo. Primeiramente, se a arma de longo alcance for uma arma de fogo, você pode dispará-la para criar um estrondo alto e concussão, utilizando o efeito de especialização crítica para armas de fogo em vez do efeito de especialização crítica do grupo de armas corpo a corpo. Em segundo lugar, você pode optar por disparar a arma de longo alcance para aumentar o momentum do acerto crítico ou atirar no oponente enquanto ataca corpo a corpo, causando 2 pontos adicionais de dano por dado de dano da arma. Ambas essas opções descarregam a arma de longo alcance, o que geralmente significa que você precisa recarregá-la antes de dispará-la novamente.'
    case Traco.Juncao: return 'Armas de Junção unem a funcionalidade de armas corpo a corpo e armas de longo alcance de maneiras únicas ou incomuns. Uma arma de junção possui uma forma ou uso de arma de longo alcance e uma forma ou uso de arma corpo a corpo. A tabela de armas de junção lista as estatísticas da arma de longo alcance primeiro e as estatísticas da arma corpo a corpo recuadas abaixo, logo acima da munição. Alternar entre o uso da arma corpo a corpo e o uso da arma de longo alcance requer uma ação de Interação. No entanto, se sua última ação foi um ataque corpo a corpo bem-sucedido contra um oponente usando uma arma de junção, você pode realizar um ataque de longo alcance com a arma de junção contra esse oponente sem alternar totalmente para o uso da arma de longo alcance, disparando a arma de longo alcance no momento do ataque corpo a corpo. Nesse caso, a arma de junção retorna ao seu uso corpo a corpo após o ataque de longo alcance. Como uma arma de junção é uma única arma com dois usos, ambos os usos compartilham quaisquer runas fundamentais. Você pode colocar uma runa de propriedade em uma arma de junção, desde que seja apropriada para qualquer um dos dois usos, mas se apenas um dos usos atender aos requisitos da runa de propriedade, os efeitos da runa de propriedade se aplicam apenas a esse uso. Por exemplo, um <i>Machado-Mosquete Vorpal</i> aplica a runa de propriedade vorpal apenas quando você o está usando como um machado. Devido à sua complexidade, armas de junção não podem ter outra arma, como uma baioneta ou estoque reforçado, presa a elas.'
    case Traco.Veicular: return 'Uma arma veicular está presa a um veículo ou é usada por uma montaria e normalmente só pode ser empunhada pelo condutor do veículo ou o cavaleiro principal da montaria. O condutor ou cavaleiro pode controlar uma arma veicular com as mesmas mãos que utilizam para conduzir o veículo ou guiar a montaria. Uma arma veicular pode ser Desarmada ao deslocar os controles (normalmente rédeas para uma montaria ou um dispositivo de direção para um veículo) das mãos do portador.'
    case Traco.AnexadaBestaArmaFogo: return 'Uma arma anexada deve ser combinada com outro equipamento para ser usada. Este traço lista a qual tipo de item a arma deve ser anexada. Você deve estar empunhando ou usando o item ao qual a arma está anexada para poder atacar com ela. Por exemplo, espinhos de escudo são anexados a um escudo, permitindo que você ataque com os espinhos em vez de com uma pancada com escudo, mas apenas se estiver empunhando o escudo. Uma arma anexada normalmente é aparafusada ou construída junto do item ao qual é anexada — e normalmente um item pode ter apenas uma arma anexada a ele. Uma arma anexada pode ser afixada em um item com 10 minutos de trabalho e um teste bem-sucedido de Manufatura CD 10; isto inclui o tempo necessário para remover a arma do item anterior, se necessário. Se um item for destruído, sua arma anexada normalmente pode ser recuperada.'
    case Traco.Demolidora: return 'Armas Demolidoras são especialmente eficazes em causar danos a objetos, estruturas e veículos. Sempre que você causar dano a um objeto (incluindo escudos e objetos animados), estrutura ou veículo com uma arma demoliora, o objeto sofre uma quantidade adicional de dano igual ao dobro do número de dados de dano da arma.'
    case Traco.Escalar: return 'A mão que segura esta arma está livre para Escalar.'
    case Traco.Preso: return 'https://2e.aonprd.com/Traits.aspx?ID=252'
    case Traco.Treinamento: return 'Uma arma de treinamento é projetada para ser usada ao treinar um animal para participar em combate, identificando o alvo para o animal atacar. Golpear uma criatura com uma arma de treinamento concede um bônus circunstancial de +1 no próximo teste de ataque do seu companheiro animal ou animal vinculado contra aquele alvo.'
    case Traco.GemeaEspada: return 'Estas armas são usadas em pares, complementando uma à outra. Quando atacar com uma arma gêmea, você adiciona um bônus de circunstância à rolagem de dano igual à quantidade de dados de dano da arma se já tiver atacado com uma arma diferente desse mesmo tipo neste turno. As armas devem ser do mesmo tipo para se beneficiarem deste traço, mas não precisam possuir as mesmas runas' 
    case Traco.GemeaBainha: return 'Estas armas são usadas em pares, complementando uma à outra. Quando atacar com uma arma gêmea, você adiciona um bônus de circunstância à rolagem de dano igual à quantidade de dados de dano da arma se já tiver atacado com uma arma diferente desse mesmo tipo neste turno. As armas devem ser do mesmo tipo para se beneficiarem deste traço, mas não precisam possuir as mesmas runas'
    case Traco.Injecao: return 'Essa arma pode ser preenchida com um veneno de ferimento. Imediatamente após um ataque bem-sucedido com a arma, você pode injetar o alvo com o veneno carregado com uma ação única de Interação. Recarregar a arma com uma nova substância requer três ações de Interação e utiliza ambas as mãos.'
    case Traco.Falange: return 'Uma arma de falange é eficaz para causar danos a oponentes em movimento. Quando você se Prepara para Atacar um oponente que se move dentro de seu alcance, até o início de seu próximo turno, os ataques com a arma de falange causam um dano adicional de precisão de 2 para cada dado de dano da arma.'
    case Traco.AnexadaEscudo: return 'Uma arma anexada deve ser combinada com outro equipamento para ser usada. Este traço lista a qual tipo de item a arma deve ser anexada. Você deve estar empunhando ou usando o item ao qual a arma está anexada para poder atacar com ela. Por exemplo, espinhos de escudo são anexados a um escudo, permitindo que você ataque com os espinhos em vez de com uma pancada com escudo, mas apenas se estiver empunhando o escudo. Uma arma anexada normalmente é aparafusada ou construída junto do item ao qual é anexada — e normalmente um item pode ter apenas uma arma anexada a ele. Uma arma anexada pode ser afixada em um item com 10 minutos de trabalho e um teste bem-sucedido de Manufatura CD 10; isto inclui o tempo necessário para remover a arma do item anterior, se necessário. Se um item for destruído, sua arma anexada normalmente pode ser recuperada.'
    case Traco.Ghoran: return 'Ghorans manufaturam e usam estas armas'
    case Traco.Geniano: return 'Genianos manufaturam e usam estas armas'
    case Traco.Ressonante: return 'Esta arma pode canalizar dano de energia. Você recebe a ação livre Conduzir Energia enquanto empunhar uma arma ressonante'
    case Traco.Clockwork: return 'Itens Clockwork são máquinas intrincadas e complexas que utilizam mecanismos de relojoaria para funcionar. Nem todos exigem corda diária, mas aqueles que o fazem possuem a habilidade "Corda" (wind-up) em suas descrições.'
    case Traco.Dificultadora: return 'Uma arma com o traço dificultadora é feita para abalar, expulsar ou tomar  controle do espaço no campo de batalha. Você pode usar uma ação de Interagir para bater a arma em um quadrado dentro do alcance da arma. Esse quadrado se torna terreno difícil até você atacar com a arma, se mover ou de alguma forma parar intencionalmente de bater a arma.'
    case Traco.Recarga1: return 'Embora todas as armas precisem de algum tempo para serem posicionadas, muitas armas de longo alcance também precisam ser carregadas e recarregadas. Esta entrada indica quantas ações de Interagir são necessárias para recarregar tais armas. Isso pode ser 0 se pegar munição e disparar a arma forem parte da mesma ação. Se um item exigir 2 ou mais ações para recarregar, o Mestre determina se elas devem ser realizadas juntas como uma atividade, ou se você pode gastar algumas dessas ações em um turno e o restante durante o próximo turno.'
    case Traco.Vanara: return 'Vanaras manufaturam e usam estas armas'
    case Traco.Vishkanya:return 'Vishkanyas manufaturam e usam estas armas'
    case Traco.Alquimico: return 'Itens alquímicos são impulsionados por reações de reagentes alquímicos. Itens alquímicos não são mágicos e não irradiam uma aura mágica.'
    case Traco.Concussivo: return 'Essas armas causam tanto dano contundente quanto perfurante. Ao determinar a resistência ou imunidade de uma criatura ao dano causado por esta arma, utilize a resistência ou imunidade mais fraca da criatura em relação a perfuração ou contusão. Por exemplo, se a criatura for imune a perfuração e não tiver resistência ou imunidade a dano contundente, ela sofreria o dano total de uma arma concussiva. Resistência ou imunidade a todo dano físico, ou a todo tipo de dano, se aplica normalmente.'
    case Traco.Repeticao: return 'Essas armas não podem ser carregadas com projéteis individuais, como virotes ou balas, como outras bestas e armas de fogo; em vez disso, elas exigem um carregador de munição especializado para ser inserido em um compartimento específico. Uma vez que o carregador esteja no lugar, a munição é carregada automaticamente cada vez que a arma é armada para atirar, reduzindo o tempo de recarga para o valor indicado na entrada de recarga (normalmente 0). Quando a munição se esgota, um novo carregador deve ser inserido, o que requer uma mão livre e 3 ações de Interação (para remover o carregador antigo, pegar o novo carregador e encaixar o novo carregador no lugar). Essas ações não precisam ser consecutivas.'
    case Traco.Recuo: return 'Uma arma de recuo é extra potente e difícil de usar devido ao seu alto recuo. Uma arma de recuo causa 1 dano adicional com todos os ataques. Disparar uma arma de recuo impõe uma penalidade circunstancial de -2 no teste de ataque, mas personagens com 14 ou mais Força ignoram essa penalidade. Anexar uma arma de recuo a um tripé, bipé ou outro estabilizador implantado pode reduzir ou anular essa penalidade.'
    case Traco.Remendado: return 'Esta arma de fogo é improvisada e propensa a falhas. Independentemente de quão bem você a mantenha, em um rolar de ataque mal-sucedido, o ataque erra e você deve fazer um teste plano com CD 5. Se falhar nesse teste, a arma falha.'
    case Traco.Disperso3m: return 'Esta arma dispara um conjunto de projéteis em um spray amplo. A Dispersão sempre tem uma área listada com ela, indicando o raio do spray. Em um acerto, o alvo principal dos ataques com uma arma de dispersão sofre o dano listado, e o alvo e todas as outras criaturas dentro do raio listado ao redor dele sofrem 1 ponto de dano de respingo por dado de dano da arma.'
    case Traco.Disperso1MetroMeio: return 'Esta arma dispara um conjunto de projéteis em um spray amplo. A Dispersão sempre tem uma área listada com ela, indicando o raio do spray. Em um acerto, o alvo principal dos ataques com uma arma de dispersão sofre o dano listado, e o alvo e todas as outras criaturas dentro do raio listado ao redor dele sofrem 1 ponto de dano de respingo por dado de dano da arma.'
    case Traco.Retornante: return 'As armas de recuperação são armas arremessadas projetadas para retornar ao arremessador quando erram o alvo. Quando você realiza um Ataque Arremessado sem sucesso com esta arma, ela retorna à sua mão após o ataque ser concluído, permitindo que você tente novamente. Se suas mãos estiverem ocupadas quando a arma retornar, ela cai no chão em seu espaço.'
    case Traco.Capacidade2: return 'Armas que possuem o traço Capacidade geralmente têm vários canos ou compartimentos capazes de conter um projétil de munição. A capacidade é sempre acompanhada por um número que indica a quantidade de canos ou compartimentos. Após disparar uma arma de capacidade, você pode selecionar o próximo cano ou compartimento carregado como uma ação de Interação que não requer uma mão livre. Cada cano ou compartimento pode ser recarregado individualmente após ser disparado como uma ação de Interação separada.'
    case Traco.Capacidade3: return 'Armas que possuem o traço Capacidade geralmente têm vários canos ou compartimentos capazes de conter um projétil de munição. A capacidade é sempre acompanhada por um número que indica a quantidade de canos ou compartimentos. Após disparar uma arma de capacidade, você pode selecionar o próximo cano ou compartimento carregado como uma ação de Interação que não requer uma mão livre. Cada cano ou compartimento pode ser recarregado individualmente após ser disparado como uma ação de Interação separada.'
    case Traco.Capacidade4: return 'Armas que possuem o traço Capacidade geralmente têm vários canos ou compartimentos capazes de conter um projétil de munição. A capacidade é sempre acompanhada por um número que indica a quantidade de canos ou compartimentos. Após disparar uma arma de capacidade, você pode selecionar o próximo cano ou compartimento carregado como uma ação de Interação que não requer uma mão livre. Cada cano ou compartimento pode ser recarregado individualmente após ser disparado como uma ação de Interação separada.'
    case Traco.Capacidade5: return 'Armas que possuem o traço Capacidade geralmente têm vários canos ou compartimentos capazes de conter um projétil de munição. A capacidade é sempre acompanhada por um número que indica a quantidade de canos ou compartimentos. Após disparar uma arma de capacidade, você pode selecionar o próximo cano ou compartimento carregado como uma ação de Interação que não requer uma mão livre. Cada cano ou compartimento pode ser recarregado individualmente após ser disparado como uma ação de Interação separada.'
    case Traco.CanoDuplo: return 'Esta arma possui dois canos, cada um carregado separadamente. Você pode disparar ambos os canos de uma arma de dois canos em um único Ataque para aumentar o dado de dano da arma em um passo. Se a arma possuir a característica fatal, isso aumenta o dado fatal em um passo.'
  }
}
