import type Arma from './model/Arma'
import { Categoria } from './model/Categoria'
import { Dano } from './model/Dano'
import { Distancia } from './model/Distancia'
import { Grupo } from './model/Grupo'
import { Raridade } from '../Utils/Raridade'
import { Tipo } from './model/Tipo'
import { TipoDano } from './model/TipoDano'
import { Traco } from './model/Traco'

export const armasBase = [
  //ARMAS SIMPLES
  {
    id: 1,
    nome: 'Adaga',
    level: 0,
    raridade: Raridade.COMUM,
    source: 'Player Core, Pg. 277',
    preco: 20,
    dano: Dano['1d4'],
    tipoDano: TipoDano.Perfurante,
    volume: 'L',
    maos: 10,
    tipo: Tipo.CAC,
    distancia: Distancia['3m'],
    categoria: Categoria.Simples,
    grupo: Grupo.Faca,
    tracos: [Traco.Arremesso3m, Traco.VersatilCt, Traco.Acuidade, Traco.Agil],
    armaEspecifica: false,
    descricao:
      'Esta pequena arma com lâmina é empunhada em uma mão e usada para apunhalar uma criatura em combate aproximado. Ela também pode ser arremessada'
  },
  {
    id: 2,
    nome: 'Lança',
    level: 0,
    raridade: Raridade.COMUM,
    source: 'Player Core, Pg. 277',
    preco: 10,
    dano: Dano['1d6'],
    tipoDano: TipoDano.Perfurante,
    volume: '1',
    maos: 1,
    tipo: Tipo.CAC,
    distancia: Distancia['6m'],
    categoria: Categoria.Simples,
    grupo: Grupo.Lanca,
    tracos: [Traco.Arremesso6m, Traco.Monge],
    armaEspecifica: false,
    descricao:
      'Composta por um longo cabo de metal e ponta com cravo do mesmo material, uma lança pode ser usada com uma mão como arma branca ou ser arremessada.'
  },
  {
    id: 3,
    nome: 'Cajado',
    level: 0,
    raridade: Raridade.COMUM,
    source: 'Player Core, Pg. 277',
    preco: 0,
    dano: Dano['1d4'],
    tipoDano: TipoDano.Contundente,
    volume: '1',
    maos: 1,
    tipo: Tipo.CAC,
    distancia: Distancia.CAC,
    categoria: Categoria.Simples,
    grupo: Grupo.Clava,
    tracos: [Traco.DuasMaosD8],
    armaEspecifica: false,
    descricao: 'Esta longa peça de madeira pode auxiliar no caminhar e desferir golpes poderosos'
  },
  {
    id: 4,
    nome: 'Clava',
    level: 0,
    raridade: Raridade.COMUM,
    source: 'Player Core, Pg. 277',
    preco: 0,
    dano: Dano['1d6'],
    tipoDano: TipoDano.Contundente,
    volume: 'L',
    maos: 1,
    tipo: Tipo.CAC,
    distancia: Distancia.CAC,
    categoria: Categoria.Simples,
    grupo: Grupo.Faca,
    tracos: [Traco.Arremesso3m],
    armaEspecifica: false,
    descricao: ""
  },
  {
    id: 5,
    nome: 'Foice',
    level: 0,
    raridade: Raridade.COMUM,
    source: 'Player Core, Pg. 277',
    preco: 20,
    dano: Dano['1d4'],
    tipoDano: TipoDano.Cortante,
    volume: 'L',
    maos: 1,
    tipo: Tipo.CAC,
    distancia: Distancia.CAC,
    categoria: Categoria.Simples,
    grupo: Grupo.Faca,
    tracos: [Traco.Acuidade, Traco.Agil, Traco.Derrubar],
    armaEspecifica: false,
    descricao: ""
  },
  {
    id: 6,
    nome: 'Lança Longa',
    level: 0,
    raridade: Raridade.COMUM,
    source: 'Player Core, Pg. 277',
    preco: 50,
    dano: Dano['1d8'],
    tipoDano: TipoDano.Perfurante,
    volume: '2',
    maos: 2,
    tipo: Tipo.CAC,
    distancia: Distancia.CAC,
    categoria: Categoria.Simples,
    grupo: Grupo.Lanca,
    tracos: [Traco.Alcance],
    armaEspecifica: false,
    descricao: ""
  },
  {
    id: 7,
    nome: 'Maça',
    level: 0,
    raridade: Raridade.COMUM,
    source: 'Player Core, Pg. 277',
    preco: 100,
    dano: Dano['1d6'],
    tipoDano: TipoDano.Contundente,
    volume: '1',
    maos: 1,
    tipo: Tipo.CAC,
    distancia: Distancia.CAC,
    categoria: Categoria.Simples,
    grupo: Grupo.Clava,
    tracos: [Traco.Empurrar],
    armaEspecifica: false,
    descricao: ""
  },
  {
    id: 8,
    nome: 'Maça Leve',
    level: 0,
    raridade: Raridade.COMUM,
    source: 'Player Core, Pg. 277',
    preco: 100,
    dano: Dano['1d4'],
    tipoDano: TipoDano.Contundente,
    volume: 'L',
    maos: 1,
    tipo: Tipo.CAC,
    distancia: Distancia.CAC,
    categoria: Categoria.Simples,
    grupo: Grupo.Clava,
    tracos: [Traco.Acuidade, Traco.Agil, Traco.Empurrar],
    armaEspecifica: false,
    descricao: ""
  },
  {
    id: 9,
    nome: 'Maça-Estrela',
    level: 0,
    raridade: Raridade.COMUM,
    source: 'Player Core, Pg. 277',
    preco: 100,
    dano: Dano['1d6'],
    tipoDano: TipoDano.Contundente,
    volume: '1',
    maos: 1,
    tipo: Tipo.CAC,
    distancia: Distancia.CAC,
    categoria: Categoria.Simples,
    grupo: Grupo.Clava,
    tracos: [Traco.VersatilPf],
    armaEspecifica: false,
    descricao: ""
  },
  {
    id: 10,
    nome: 'Manopla',
    level: 0,
    raridade: Raridade.COMUM,
    source: 'Player Core, Pg. 277',
    preco: 20,
    dano: Dano['1d4'],
    tipoDano: TipoDano.Contundente,
    volume: 'L',
    maos: 1,
    tipo: Tipo.CAC,
    distancia: Distancia.CAC,
    categoria: Categoria.Simples,
    grupo: Grupo.Pugilato,
    tracos: [Traco.Agil, Traco.MaoLivre],
    armaEspecifica: false,
    descricao: ""
  },
  {
    id: 11,
    nome: 'Manopla com Cravos',
    level: 0,
    raridade: Raridade.COMUM,
    source: 'Player Core, Pg. 277',
    preco: 30,
    dano: Dano['1d4'],
    tipoDano: TipoDano.Perfurante,
    volume: 'L',
    maos: 1,
    tipo: Tipo.CAC,
    distancia: Distancia.CAC,
    categoria: Categoria.Simples,
    grupo: Grupo.Pugilato,
    tracos: [Traco.Agil, Traco.MaoLivre],
    armaEspecifica: false,
    descricao: ""
  },
  {
    id: 12,
    nome: 'Adaga de Clã',
    level: 0,
    raridade: Raridade.INCOMUM,
    source: 'Player Core, Pg. 277',
    preco: 200,
    dano: Dano['1d4'],
    tipoDano: TipoDano.Perfurante,
    volume: 'L',
    maos: 1,
    tipo: Tipo.CAC,
    distancia: Distancia.CAC,
    categoria: Categoria.Simples,
    grupo: Grupo.Faca,
    tracos: [Traco.Agil, Traco.Anao, Traco.VersatilCn],
    armaEspecifica: false,
    descricao: ""
  },
  {
    id: 13,
    nome: 'Katar',
    level: 0,
    raridade: Raridade.INCOMUM,
    source: 'Player Core, Pg. 277',
    preco: 30,
    dano: Dano['1d4'],
    tipoDano: TipoDano.Perfurante,
    volume: 'L',
    maos: 1,
    tipo: Tipo.CAC,
    distancia: Distancia.CAC,
    categoria: Categoria.Simples,
    grupo: Grupo.Faca,
    tracos: [Traco.Agil, Traco.MortalD6, Traco.Monge],
    armaEspecifica: false,
    descricao: ""
  },
  {
    id: 14,
    nome: 'Azagaia',
    level: 0,
    raridade: Raridade.COMUM,
    source: 'Player Core, Pg. 281',
    preco: 10,
    dano: Dano['1d6'],
    tipoDano: TipoDano.Perfurante,
    volume: 'L',
    maos: 1,
    tipo: Tipo.Ranged,
    distancia: Distancia['9m'],
    categoria: Categoria.Simples,
    grupo: Grupo.Dardo,
    tracos: [Traco.Arremesso],
    armaEspecifica: false,
    descricao: ""
  },
  {
    id: 15,
    nome: 'Besta Leve',
    level: 0,
    raridade: Raridade.COMUM,
    source: 'Player Core, Pg. 281',
    preco: 300,
    dano: Dano['1d8'],
    tipoDano: TipoDano.Perfurante,
    volume: '1',
    maos: 2,
    tipo: Tipo.Ranged,
    distancia: Distancia['36m'],
    categoria: Categoria.Simples,
    grupo: Grupo.Besta,
    tracos: [],
    armaEspecifica: false,
    descricao: ""
  },
  {
    id: 16,
    nome: 'Besta de Mão',
    level: 0,
    raridade: Raridade.COMUM,
    source: 'Player Core, Pg. 281',
    preco: 300,
    dano: Dano['1d6'],
    tipoDano: TipoDano.Perfurante,
    volume: 'L',
    maos: 1,
    tipo: Tipo.Ranged,
    distancia: Distancia['18m'],
    categoria: Categoria.Simples,
    grupo: Grupo.Besta,
    tracos: [],
    armaEspecifica: false,
    descricao: ""
  },
  {
    id: 16,
    nome: 'Besta Pesada',
    level: 0,
    raridade: Raridade.COMUM,
    source: 'Player Core, Pg. 281',
    preco: 400,
    dano: Dano['1d10'],
    tipoDano: TipoDano.Perfurante,
    volume: '2',
    maos: 2,
    tipo: Tipo.Ranged,
    distancia: Distancia['36m'],
    categoria: Categoria.Simples,
    grupo: Grupo.Besta,
    tracos: [],
    armaEspecifica: false,
    descricao: ""
  },
  //ARMAS MARCIAIS
  {
    id: 4,
    nome: 'Espada Longa',
    level: 0,
    raridade: Raridade.COMUM,
    source: 'Core Rulebook pg. 281',
    preco: 100,
    dano: Dano['1d8'],
    tipoDano: TipoDano.Cortante,
    volume: '1',
    maos: 1,
    tipo: Tipo.CAC,
    distancia: Distancia.CAC,
    categoria: Categoria.Marcial,
    grupo: Grupo.Espada,
    tracos: [Traco.VersatilPf],
    armaEspecifica: false,
    descricao:
      'Espadas longas podem ser espadas de um ou dois gumes. Suas lâminas são pesadas e elas possuem de 0,9 a 1,2 metros de comprimento.'
  },
  {
    id: 5,
    nome: 'Segadeira',
    level: 0,
    raridade: Raridade.COMUM,
    source: 'Core Rulebook pg. 281',
    preco: 200,
    dano: Dano['1d10'],
    tipoDano: TipoDano.Cortante,
    volume: '2',
    maos: 2,
    tipo: Tipo.CAC,
    distancia: Distancia.CAC,
    categoria: Categoria.Marcial,
    grupo: Grupo.Haste,
    tracos: [Traco.Derrubar, Traco.MortalD10],
    armaEspecifica: false,
    descricao:
      'Derivada de uma ferramenta agrícola usada para ceifar grãos e cereais longos, esta arma possui um cabo comprido de madeira com empunhaduras protuberantes, encimado por uma lâmina curva ajustada em um ângulo reto.'
  },
  {
    id: 6,
    nome: 'Chicote',
    level: 0,
    raridade: Raridade.COMUM,
    source: 'Core Rulebook pg. 281',
    preco: 200,
    dano: Dano['1d4'],
    tipoDano: TipoDano.Cortante,
    volume: '1',
    maos: 1,
    tipo: Tipo.CAC,
    distancia: Distancia.CAC,
    categoria: Categoria.Marcial,
    grupo: Grupo.Mangual,
    tracos: [Traco.Desarmar, Traco.Acuidade, Traco.NaoLetal, Traco.Alcance, Traco.Derrubar],
    armaEspecifica: false,
    descricao:
      'Este longo cabo de couro grosso, frequentemente trançado, causa um corte doloroso, mas não-letal, à distância, normalmente acompanhado por um estalo bem distinto'
  },
  {
    id: 7,
    nome: 'Machado de Guerra Enânico',
    level: 0,
    raridade: Raridade.INCOMUM,
    source: 'Core Rulebook pg. 281',
    preco: 300,
    dano: Dano['1d8'],
    tipoDano: TipoDano.Cortante,
    volume: '2',
    maos: 1,
    tipo: Tipo.CAC,
    distancia: Distancia.CAC,
    categoria: Categoria.Avancada,
    grupo: Grupo.Machado,
    tracos: [Traco.Amplitude, Traco.Anao, Traco.DuasMaosD12],
    armaEspecifica: false,
    descricao:
      'Esta arma favorecida por anões possui uma grande cabeça ornamentada montada em um cabo grosso. Este poderoso machado pode ser empunhado com uma ou duas mãos.'
  },
  {
    id: 8,
    nome: 'Maça-Chicote Gnômica',
    level: 0,
    raridade: Raridade.INCOMUM,
    source: 'Core Rulebook pg. 281',
    preco: 300,
    dano: Dano['1d8'],
    tipoDano: TipoDano.Contundente,
    volume: '2',
    maos: 1,
    tipo: Tipo.CAC,
    distancia: Distancia.CAC,
    categoria: Categoria.Avancada,
    grupo: Grupo.Mangual,
    tracos: [Traco.Alcance, Traco.Gnomo],
    armaEspecifica: false,
    descricao:
      'Mais um mangual do que uma maça, esta arma possui um cabo curto conectado a uma corrente com uma bola em seu fim. A bola é propelida com um movimento do pulso, sendo que o próprio impulso traz a bola de volta para o usuário após o golpe.'
  },
  {
    id: 9,
    nome: 'Sabre Serrilhado',
    level: 0,
    raridade: Raridade.INCOMUM,
    source: 'Core Rulebook pg. 281',
    preco: 500,
    dano: Dano['1d6'],
    tipoDano: TipoDano.Cortante,
    volume: 'L',
    maos: 1,
    tipo: Tipo.CAC,
    distancia: Distancia.CAC,
    categoria: Categoria.Avancada,
    grupo: Grupo.Espada,
    tracos: [Traco.Acuidade, Traco.Agil, Traco.Gemea],
    armaEspecifica: false,
    descricao:
      'A marca registrada dos assassinos do Louva-a-Deus Vermelho, esta lâmina curva é semelhante a uma serra — daí seu nome'
  },
] as Arma[]

export const armasEspecificas = [
  {
    id: 10,
    nome: 'Vingadora Sagrada',
    level: 14,
    raridade: Raridade.INCOMUM,
    source: 'Core Rulebook pg. 601',
    preco: 450000,
    dano: Dano['1d8'],
    tipoDano: TipoDano.Cortante,
    volume: '1',
    maos: 1,
    tipo: Tipo.CAC,
    distancia: Distancia.CAC,
    categoria: Categoria.Marcial,
    grupo: Grupo.Espada,
    tracos: [Traco.VersatilPf, Traco.Divino],
    armaEspecifica: true,
    descricao:
      'A reluzente vingadora sagrada é a arma icônica dos paladinos poderosos. A guarda-mão desta espada longa de ferro frio +2 impactante maior sagrada é estilizada para parecer as asas de um anjo. A tradição diz que aqueles que veem seus reflexos na lâmina altamente polida de uma vingadora sagrada têm suas falhas reveladas. Se for maligno, você fica enfraquecido 2 enquanto carregar ou empunhar esta arma.'
  }
] as Arma[]
